import { Player } from "../types";

// Mock data for home and away teams
export const mockHomePlayers: Player[] = [
  {
    name: "Lebron James",
    number: "6",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Anthony Davis",
    number: "3",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Austin Reaves",
    number: "15",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "D'Angelo Russell",
    number: "1",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Rui Hachimura",
    number: "28",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Jarred Vanderbilt",
    number: "2",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Gabe Vincent",
    number: "7",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Taurean Prince",
    number: "12",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Max Christie",
    number: "10",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Jaxson Hayes",
    number: "11",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
];

export const mockAwayPlayers: Player[] = [
  {
    name: "Stephen Curry",
    number: "30",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Klay Thompson",
    number: "11",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Draymond Green",
    number: "23",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Andrew Wiggins",
    number: "22",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Kevon Looney",
    number: "5",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Chris Paul",
    number: "3",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Jonathan Kuminga",
    number: "00",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Gary Payton II",
    number: "8",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Moses Moody",
    number: "4",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
  {
    name: "Dario Saric",
    number: "20",
    points: 0,
    freeThrow: { made: 0, attempted: 0 },
    twoPointer: { made: 0, attempted: 0 },
    threePointer: { made: 0, attempted: 0 },
    assists: 0,
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
    fouls: 0,
  },
];
